[package]
name = "CetusClmm"
version = "mainnet-v1.3.0"
edition = "2024"

[dependencies]
MoveSTL = { git = "https://github.com/CetusProtocol/move-stl.git", rev = "mainnet-v1.3.0", override = true }
CetusIntegerMate = { git = "https://github.com/luck-28/cetus-integer-mate.git", rev = "main", override = true }

[addresses]
cetus_clmm = "0x1eabed72c53feb3805120a081dc15963c204dc8d091542592abaf7a35689b2fb"
